# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `repost` gem.
# Please instead update this file by running `bin/tapioca gem repost`.

class ActionController::Base < ::ActionController::Metal
  include ::ActionDispatch::Routing::PolymorphicRoutes
  include ::ActionController::Head
  include ::AbstractController::Caching::ConfigMethods
  include ::ActionController::BasicImplicitRender

  # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#68
  def __callbacks; end

  # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#68
  def __callbacks?; end

  # source://actionpack/7.0.4.3/lib/abstract_controller/helpers.rb#11
  def _helper_methods; end

  # source://actionpack/7.0.4.3/lib/abstract_controller/helpers.rb#11
  def _helper_methods=(_arg0); end

  # source://actionpack/7.0.4.3/lib/abstract_controller/helpers.rb#11
  def _helper_methods?; end

  # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#940
  def _process_action_callbacks; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/renderers.rb#31
  def _renderers; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/renderers.rb#31
  def _renderers=(_arg0); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/renderers.rb#31
  def _renderers?; end

  # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#928
  def _run_process_action_callbacks(&block); end

  # source://actionpack/7.0.4.3/lib/abstract_controller/caching.rb#42
  def _view_cache_dependencies; end

  # source://actionpack/7.0.4.3/lib/abstract_controller/caching.rb#42
  def _view_cache_dependencies=(_arg0); end

  # source://actionpack/7.0.4.3/lib/abstract_controller/caching.rb#42
  def _view_cache_dependencies?; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/params_wrapper.rb#185
  def _wrapper_options; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/params_wrapper.rb#185
  def _wrapper_options=(_arg0); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/params_wrapper.rb#185
  def _wrapper_options?; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/flash.rb#36
  def alert; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def allow_forgery_protection; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def allow_forgery_protection=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def asset_host; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def asset_host=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def assets_dir; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def assets_dir=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def default_asset_host_protocol; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def default_asset_host_protocol=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def default_protect_from_forgery; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def default_protect_from_forgery=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def default_static_extension; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def default_static_extension=(value); end

  # source://actionpack/7.0.4.3/lib/action_dispatch/routing/url_for.rb#95
  def default_url_options; end

  # source://actionpack/7.0.4.3/lib/action_dispatch/routing/url_for.rb#95
  def default_url_options=(_arg0); end

  # source://actionpack/7.0.4.3/lib/action_dispatch/routing/url_for.rb#95
  def default_url_options?; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def enable_fragment_cache_logging; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def enable_fragment_cache_logging=(value); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/etag_with_template_digest.rb#27
  def etag_with_template_digest; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/etag_with_template_digest.rb#27
  def etag_with_template_digest=(_arg0); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/etag_with_template_digest.rb#27
  def etag_with_template_digest?; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/conditional_get.rb#13
  def etaggers; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/conditional_get.rb#13
  def etaggers=(_arg0); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/conditional_get.rb#13
  def etaggers?; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/flash.rb#10
  def flash(*_arg0, **_arg1, &_arg2); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def forgery_protection_origin_check; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def forgery_protection_origin_check=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def forgery_protection_strategy; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def forgery_protection_strategy=(value); end

  # source://actionpack/7.0.4.3/lib/abstract_controller/caching/fragments.rb#23
  def fragment_cache_keys; end

  # source://actionpack/7.0.4.3/lib/abstract_controller/caching/fragments.rb#23
  def fragment_cache_keys=(_arg0); end

  # source://actionpack/7.0.4.3/lib/abstract_controller/caching/fragments.rb#23
  def fragment_cache_keys?; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#63
  def helpers_path; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#63
  def helpers_path=(_arg0); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#63
  def helpers_path?; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#64
  def include_all_helpers; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#64
  def include_all_helpers=(_arg0); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#64
  def include_all_helpers?; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def javascripts_dir; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def javascripts_dir=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def log_warning_on_csrf_failure; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def log_warning_on_csrf_failure=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def logger; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def logger=(value); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/flash.rb#36
  def notice; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def per_form_csrf_tokens; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def per_form_csrf_tokens=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def perform_caching; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def perform_caching=(value); end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/redirecting.rb#13
  def raise_on_open_redirects; end

  # source://actionpack/7.0.4.3/lib/action_controller/metal/redirecting.rb#13
  def raise_on_open_redirects=(val); end

  # source://repost//lib/repost/extend_controller.rb#5
  def redirect_post(url, params: T.unsafe(nil), options: T.unsafe(nil)); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def relative_url_root; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def relative_url_root=(value); end

  # source://repost//lib/repost/extend_controller.rb#5
  def repost(url, params: T.unsafe(nil), options: T.unsafe(nil)); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def request_forgery_protection_token; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def request_forgery_protection_token=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/rescuable.rb#13
  def rescue_handlers; end

  # source://activesupport/7.0.4.3/lib/active_support/rescuable.rb#13
  def rescue_handlers=(_arg0); end

  # source://activesupport/7.0.4.3/lib/active_support/rescuable.rb#13
  def rescue_handlers?; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def stylesheets_dir; end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
  def stylesheets_dir=(value); end

  # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
  def urlsafe_csrf_tokens; end

  private

  # source://actionview/7.0.4.3/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats); end

  # source://actionpack/7.0.4.3/lib/action_controller/base.rb#266
  def _protected_ivars; end

  class << self
    # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#68
    def __callbacks; end

    # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#68
    def __callbacks=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#68
    def __callbacks?; end

    # source://actionpack/7.0.4.3/lib/action_controller/form_builder.rb#31
    def _default_form_builder; end

    # source://actionpack/7.0.4.3/lib/action_controller/form_builder.rb#31
    def _default_form_builder=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/form_builder.rb#31
    def _default_form_builder?; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/flash.rb#8
    def _flash_types; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/flash.rb#8
    def _flash_types=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/flash.rb#8
    def _flash_types?; end

    # source://actionpack/7.0.4.3/lib/abstract_controller/helpers.rb#11
    def _helper_methods; end

    # source://actionpack/7.0.4.3/lib/abstract_controller/helpers.rb#11
    def _helper_methods=(value); end

    # source://actionpack/7.0.4.3/lib/abstract_controller/helpers.rb#11
    def _helper_methods?; end

    # source://actionpack/7.0.4.3/lib/abstract_controller/helpers.rb#15
    def _helpers; end

    # source://actionview/7.0.4.3/lib/action_view/layouts.rb#209
    def _layout; end

    # source://actionview/7.0.4.3/lib/action_view/layouts.rb#209
    def _layout=(value); end

    # source://actionview/7.0.4.3/lib/action_view/layouts.rb#209
    def _layout?; end

    # source://actionview/7.0.4.3/lib/action_view/layouts.rb#210
    def _layout_conditions; end

    # source://actionview/7.0.4.3/lib/action_view/layouts.rb#210
    def _layout_conditions=(value); end

    # source://actionview/7.0.4.3/lib/action_view/layouts.rb#210
    def _layout_conditions?; end

    # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#932
    def _process_action_callbacks; end

    # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#936
    def _process_action_callbacks=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/renderers.rb#31
    def _renderers; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/renderers.rb#31
    def _renderers=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/renderers.rb#31
    def _renderers?; end

    # source://actionpack/7.0.4.3/lib/abstract_controller/caching.rb#42
    def _view_cache_dependencies; end

    # source://actionpack/7.0.4.3/lib/abstract_controller/caching.rb#42
    def _view_cache_dependencies=(value); end

    # source://actionpack/7.0.4.3/lib/abstract_controller/caching.rb#42
    def _view_cache_dependencies?; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/params_wrapper.rb#185
    def _wrapper_options; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/params_wrapper.rb#185
    def _wrapper_options=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/params_wrapper.rb#185
    def _wrapper_options?; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def allow_forgery_protection; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def allow_forgery_protection=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def asset_host; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def asset_host=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def assets_dir; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def assets_dir=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def default_asset_host_protocol; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def default_asset_host_protocol=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def default_protect_from_forgery; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def default_protect_from_forgery=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def default_static_extension; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def default_static_extension=(value); end

    # source://actionpack/7.0.4.3/lib/action_dispatch/routing/url_for.rb#95
    def default_url_options; end

    # source://actionpack/7.0.4.3/lib/action_dispatch/routing/url_for.rb#95
    def default_url_options=(value); end

    # source://actionpack/7.0.4.3/lib/action_dispatch/routing/url_for.rb#95
    def default_url_options?; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def enable_fragment_cache_logging; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def enable_fragment_cache_logging=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/etag_with_template_digest.rb#27
    def etag_with_template_digest; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/etag_with_template_digest.rb#27
    def etag_with_template_digest=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/etag_with_template_digest.rb#27
    def etag_with_template_digest?; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/conditional_get.rb#13
    def etaggers; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/conditional_get.rb#13
    def etaggers=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/conditional_get.rb#13
    def etaggers?; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def forgery_protection_origin_check; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def forgery_protection_origin_check=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def forgery_protection_strategy; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def forgery_protection_strategy=(value); end

    # source://actionpack/7.0.4.3/lib/abstract_controller/caching/fragments.rb#23
    def fragment_cache_keys; end

    # source://actionpack/7.0.4.3/lib/abstract_controller/caching/fragments.rb#23
    def fragment_cache_keys=(value); end

    # source://actionpack/7.0.4.3/lib/abstract_controller/caching/fragments.rb#23
    def fragment_cache_keys?; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#63
    def helpers_path; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#63
    def helpers_path=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#63
    def helpers_path?; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#64
    def include_all_helpers; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#64
    def include_all_helpers=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/helpers.rb#64
    def include_all_helpers?; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def javascripts_dir; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def javascripts_dir=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def log_warning_on_csrf_failure; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def log_warning_on_csrf_failure=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def logger; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def logger=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal.rb#210
    def middleware_stack; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def per_form_csrf_tokens; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def per_form_csrf_tokens=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def perform_caching; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def perform_caching=(value); end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/redirecting.rb#13
    def raise_on_open_redirects; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/redirecting.rb#13
    def raise_on_open_redirects=(val); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def relative_url_root; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def relative_url_root=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def request_forgery_protection_token; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def request_forgery_protection_token=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/rescuable.rb#13
    def rescue_handlers; end

    # source://activesupport/7.0.4.3/lib/active_support/rescuable.rb#13
    def rescue_handlers=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/rescuable.rb#13
    def rescue_handlers?; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def stylesheets_dir; end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#114
    def stylesheets_dir=(value); end

    # source://activesupport/7.0.4.3/lib/active_support/configurable.rb#113
    def urlsafe_csrf_tokens; end

    # source://actionpack/7.0.4.3/lib/action_controller/metal/request_forgery_protection.rb#97
    def urlsafe_csrf_tokens=(urlsafe_csrf_tokens); end

    # source://actionpack/7.0.4.3/lib/action_controller/base.rb#198
    def without_modules(*modules); end
  end
end

# source://repost//lib/repost/version.rb#1
module Repost; end

# source://repost//lib/repost/action.rb#2
class Repost::Action
  class << self
    # source://repost//lib/repost/action.rb#3
    def perform(*args, **kw_args); end
  end
end

# source://repost//lib/repost.rb#7
class Repost::Error < ::StandardError; end

# source://repost//lib/repost/senpai.rb#2
class Repost::Senpai < ::Repost::Action
  # @return [Senpai] a new instance of Senpai
  #
  # source://repost//lib/repost/senpai.rb#6
  def initialize(url, params: T.unsafe(nil), options: T.unsafe(nil)); end

  # source://repost//lib/repost/senpai.rb#22
  def perform; end

  private

  # Returns the value of attribute authenticity_token.
  #
  # source://repost//lib/repost/senpai.rb#33
  def authenticity_token; end

  # source://repost//lib/repost/senpai.rb#89
  def auto_submit_script; end

  # Returns the value of attribute autosubmit.
  #
  # source://repost//lib/repost/senpai.rb#33
  def autosubmit; end

  # Returns the value of attribute autosubmit_nonce.
  #
  # source://repost//lib/repost/senpai.rb#33
  def autosubmit_nonce; end

  # Returns the value of attribute charset.
  #
  # source://repost//lib/repost/senpai.rb#33
  def charset; end

  # source://repost//lib/repost/senpai.rb#68
  def csrf_token; end

  # source://repost//lib/repost/senpai.rb#41
  def form_body; end

  # source://repost//lib/repost/senpai.rb#64
  def form_footer; end

  # source://repost//lib/repost/senpai.rb#37
  def form_head; end

  # Returns the value of attribute form_id.
  #
  # source://repost//lib/repost/senpai.rb#33
  def form_id; end

  # source://repost//lib/repost/senpai.rb#49
  def form_input(key, value); end

  # source://repost//lib/repost/senpai.rb#85
  def generated_form_id; end

  # Returns the value of attribute method.
  #
  # source://repost//lib/repost/senpai.rb#33
  def method; end

  # source://repost//lib/repost/senpai.rb#72
  def no_script; end

  # Returns the value of attribute options.
  #
  # source://repost//lib/repost/senpai.rb#33
  def options; end

  # Returns the value of attribute params.
  #
  # source://repost//lib/repost/senpai.rb#33
  def params; end

  # source://repost//lib/repost/senpai.rb#96
  def process_value(value); end

  # Returns the value of attribute section_classes.
  #
  # source://repost//lib/repost/senpai.rb#33
  def section_classes; end

  # Returns the value of attribute section_html.
  #
  # source://repost//lib/repost/senpai.rb#33
  def section_html; end

  # Returns the value of attribute submit_classes.
  #
  # source://repost//lib/repost/senpai.rb#33
  def submit_classes; end

  # source://repost//lib/repost/senpai.rb#78
  def submit_section; end

  # Returns the value of attribute submit_text.
  #
  # source://repost//lib/repost/senpai.rb#33
  def submit_text; end

  # Returns the value of attribute url.
  #
  # source://repost//lib/repost/senpai.rb#33
  def url; end
end

# source://repost//lib/repost/senpai.rb#4
Repost::Senpai::DEFAULT_CHARSET = T.let(T.unsafe(nil), String)

# source://repost//lib/repost/senpai.rb#3
Repost::Senpai::DEFAULT_SUBMIT_BUTTON_TEXT = T.let(T.unsafe(nil), String)

# source://repost//lib/repost/version.rb#2
Repost::VERSION = T.let(T.unsafe(nil), String)
