# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class UserMailer
  sig { returns(ActionMailer::MessageDelivery) }
  def self.change_email; end

  sig { returns(ActionMailer::MessageDelivery) }
  def self.invited_user; end

  sig { returns(ActionMailer::MessageDelivery) }
  def self.new_password; end

  sig { returns(ActionMailer::MessageDelivery) }
  def self.new_user; end
end
