# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::ActionController::API; end
module ::ActionMailer::Base; end
module ::ActiveRecord::Base; end
module ApplicationController::ActiveRecord::RecordNotFound; end
module JsonWebToken::ActiveSupport::Concern; end
module JsonWebToken::HashWithIndifferentAccess; end
module JsonWebToken::JWT; end
module JsonWebToken::Rails; end
